version: '3.8'

services:
  backend:
    build: ./backend 
    image: mjix/backend:V2.2
    container_name: backend-container
    ports:
      -"5000:5000"
    networks:
      - my_network
    depends_on:
      -mongo

  client:
    build : ./client 
    image: mjix/backend:V2.3
    container_name: client
    networks:
      - my_network 
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongo-data:/var/lib/data/db

networks:
  app-net : 
    name : my_network
    driver: bridge
    attachable : true

volumes:
  mongo-data:
    driver: local