version: '3.8'

services:
  backend:
    image: mjix/backend:V2.2
    container_name: backend
    networks:
      - my_network
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  client:
    image: mjix/client:v1.0.1
    container_name: client
    networks:
      - my_network
    ports:
      - "3000:3000"sudi

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - my_network
    volumes:
      - mongo-data:/data/db

networks:
  my_network:

volumes:
  mongo-data:
