---
- name: Provisioning and deployment
  hosts: all
  become: yes
  vars_files:
    - var.yml

  tasks:
    - name: Update
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Create Docker network
      docker_network:
        name: "{{ network_name }}"
        state: present

    - name: Create Mongo volume
      docker_volume:
        name: "{{ mongo_volume }}"
        state: present


    - name: Copy hosts file
      copy:
        src: hosts
        dest: /etc/hosts

    - name: Copy docker-compose file
      copy:
        src: docker-compose.yaml
        dest: /home/yolo/docker-compose.yaml

    - name: Start services with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/yolo

  my_roles:
    - backend
    - datadase
    - client 