---
- name: Setup yolo
  hosts: 
  become: true
  vars_files:
  -vars/dockersetup.yaml
  -vars/myfile.yml 

  roles:
    - role: clone
    - role: docker
    - role: compose
  

  task:
    - name: Clone repository
      git:
          repo: 'https://github.com/jeremymordecai628/yolo.git'
          dest: /home/vagrant/webapp
          version: master