apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: client
        image:  mjix/backend:V2.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000



