apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_client
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: client
        image:  mjix/client:v1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: client_service
spec:
  selector:
    app: client
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
